// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/gossip.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Surf.Proto {

  /// <summary>Holder for reflection information generated from Proto/gossip.proto</summary>
  public static partial class GossipReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/gossip.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GossipReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJQcm90by9nb3NzaXAucHJvdG8SBHN1cmYaFXByb3RvL2Jhc2VUeXBlcy5w",
            "cm90byKoAQoOR29zc2lwRW52ZWxvcGUSKAoKbWVtYmVyTGVmdBgBIAEoCzIS",
            "LnN1cmYuTWVtYmVyTGVmdE1lSAASLAoMbWVtYmVySm9pbmVkGAIgASgLMhQu",
            "c3VyZi5NZW1iZXJKb2luZWRNZUgAEi8KDG1lbWJlckZhaWxlZBgDIAEoCzIX",
            "LnN1cmYuTWVtYmVyRmFpbGVkRm9yTWVIAEINCgttZXNzYWdlVHlwZSIzCgxN",
            "ZW1iZXJMZWZ0TWUSIwoGbWVtYmVyGAEgASgLMhMuc3VyZi5NZW1iZXJBZGRy",
            "ZXNzIjUKDk1lbWJlckpvaW5lZE1lEiMKBm1lbWJlchgBIAEoCzITLnN1cmYu",
            "TWVtYmVyQWRkcmVzcyI4ChFNZW1iZXJGYWlsZWRGb3JNZRIjCgZtZW1iZXIY",
            "ASABKAsyEy5zdXJmLk1lbWJlckFkZHJlc3NCDaoCClN1cmYuUHJvdG9iBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Surf.Proto.BaseTypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Surf.Proto.GossipEnvelope), global::Surf.Proto.GossipEnvelope.Parser, new[]{ "MemberLeft", "MemberJoined", "MemberFailed" }, new[]{ "MessageType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Surf.Proto.MemberLeftMe), global::Surf.Proto.MemberLeftMe.Parser, new[]{ "Member" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Surf.Proto.MemberJoinedMe), global::Surf.Proto.MemberJoinedMe.Parser, new[]{ "Member" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Surf.Proto.MemberFailedForMe), global::Surf.Proto.MemberFailedForMe.Parser, new[]{ "Member" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GossipEnvelope : pb::IMessage<GossipEnvelope> {
    private static readonly pb::MessageParser<GossipEnvelope> _parser = new pb::MessageParser<GossipEnvelope>(() => new GossipEnvelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GossipEnvelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Surf.Proto.GossipReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GossipEnvelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GossipEnvelope(GossipEnvelope other) : this() {
      switch (other.MessageTypeCase) {
        case MessageTypeOneofCase.MemberLeft:
          MemberLeft = other.MemberLeft.Clone();
          break;
        case MessageTypeOneofCase.MemberJoined:
          MemberJoined = other.MemberJoined.Clone();
          break;
        case MessageTypeOneofCase.MemberFailed:
          MemberFailed = other.MemberFailed.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GossipEnvelope Clone() {
      return new GossipEnvelope(this);
    }

    /// <summary>Field number for the "memberLeft" field.</summary>
    public const int MemberLeftFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.MemberLeftMe MemberLeft {
      get { return messageTypeCase_ == MessageTypeOneofCase.MemberLeft ? (global::Surf.Proto.MemberLeftMe) messageType_ : null; }
      set {
        messageType_ = value;
        messageTypeCase_ = value == null ? MessageTypeOneofCase.None : MessageTypeOneofCase.MemberLeft;
      }
    }

    /// <summary>Field number for the "memberJoined" field.</summary>
    public const int MemberJoinedFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.MemberJoinedMe MemberJoined {
      get { return messageTypeCase_ == MessageTypeOneofCase.MemberJoined ? (global::Surf.Proto.MemberJoinedMe) messageType_ : null; }
      set {
        messageType_ = value;
        messageTypeCase_ = value == null ? MessageTypeOneofCase.None : MessageTypeOneofCase.MemberJoined;
      }
    }

    /// <summary>Field number for the "memberFailed" field.</summary>
    public const int MemberFailedFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.MemberFailedForMe MemberFailed {
      get { return messageTypeCase_ == MessageTypeOneofCase.MemberFailed ? (global::Surf.Proto.MemberFailedForMe) messageType_ : null; }
      set {
        messageType_ = value;
        messageTypeCase_ = value == null ? MessageTypeOneofCase.None : MessageTypeOneofCase.MemberFailed;
      }
    }

    private object messageType_;
    /// <summary>Enum of possible cases for the "messageType" oneof.</summary>
    public enum MessageTypeOneofCase {
      None = 0,
      MemberLeft = 1,
      MemberJoined = 2,
      MemberFailed = 3,
    }
    private MessageTypeOneofCase messageTypeCase_ = MessageTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageTypeOneofCase MessageTypeCase {
      get { return messageTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMessageType() {
      messageTypeCase_ = MessageTypeOneofCase.None;
      messageType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GossipEnvelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GossipEnvelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MemberLeft, other.MemberLeft)) return false;
      if (!object.Equals(MemberJoined, other.MemberJoined)) return false;
      if (!object.Equals(MemberFailed, other.MemberFailed)) return false;
      if (MessageTypeCase != other.MessageTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (messageTypeCase_ == MessageTypeOneofCase.MemberLeft) hash ^= MemberLeft.GetHashCode();
      if (messageTypeCase_ == MessageTypeOneofCase.MemberJoined) hash ^= MemberJoined.GetHashCode();
      if (messageTypeCase_ == MessageTypeOneofCase.MemberFailed) hash ^= MemberFailed.GetHashCode();
      hash ^= (int) messageTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (messageTypeCase_ == MessageTypeOneofCase.MemberLeft) {
        output.WriteRawTag(10);
        output.WriteMessage(MemberLeft);
      }
      if (messageTypeCase_ == MessageTypeOneofCase.MemberJoined) {
        output.WriteRawTag(18);
        output.WriteMessage(MemberJoined);
      }
      if (messageTypeCase_ == MessageTypeOneofCase.MemberFailed) {
        output.WriteRawTag(26);
        output.WriteMessage(MemberFailed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (messageTypeCase_ == MessageTypeOneofCase.MemberLeft) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MemberLeft);
      }
      if (messageTypeCase_ == MessageTypeOneofCase.MemberJoined) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MemberJoined);
      }
      if (messageTypeCase_ == MessageTypeOneofCase.MemberFailed) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MemberFailed);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GossipEnvelope other) {
      if (other == null) {
        return;
      }
      switch (other.MessageTypeCase) {
        case MessageTypeOneofCase.MemberLeft:
          if (MemberLeft == null) {
            MemberLeft = new global::Surf.Proto.MemberLeftMe();
          }
          MemberLeft.MergeFrom(other.MemberLeft);
          break;
        case MessageTypeOneofCase.MemberJoined:
          if (MemberJoined == null) {
            MemberJoined = new global::Surf.Proto.MemberJoinedMe();
          }
          MemberJoined.MergeFrom(other.MemberJoined);
          break;
        case MessageTypeOneofCase.MemberFailed:
          if (MemberFailed == null) {
            MemberFailed = new global::Surf.Proto.MemberFailedForMe();
          }
          MemberFailed.MergeFrom(other.MemberFailed);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Surf.Proto.MemberLeftMe subBuilder = new global::Surf.Proto.MemberLeftMe();
            if (messageTypeCase_ == MessageTypeOneofCase.MemberLeft) {
              subBuilder.MergeFrom(MemberLeft);
            }
            input.ReadMessage(subBuilder);
            MemberLeft = subBuilder;
            break;
          }
          case 18: {
            global::Surf.Proto.MemberJoinedMe subBuilder = new global::Surf.Proto.MemberJoinedMe();
            if (messageTypeCase_ == MessageTypeOneofCase.MemberJoined) {
              subBuilder.MergeFrom(MemberJoined);
            }
            input.ReadMessage(subBuilder);
            MemberJoined = subBuilder;
            break;
          }
          case 26: {
            global::Surf.Proto.MemberFailedForMe subBuilder = new global::Surf.Proto.MemberFailedForMe();
            if (messageTypeCase_ == MessageTypeOneofCase.MemberFailed) {
              subBuilder.MergeFrom(MemberFailed);
            }
            input.ReadMessage(subBuilder);
            MemberFailed = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class MemberLeftMe : pb::IMessage<MemberLeftMe> {
    private static readonly pb::MessageParser<MemberLeftMe> _parser = new pb::MessageParser<MemberLeftMe>(() => new MemberLeftMe());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MemberLeftMe> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Surf.Proto.GossipReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberLeftMe() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberLeftMe(MemberLeftMe other) : this() {
      member_ = other.member_ != null ? other.member_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberLeftMe Clone() {
      return new MemberLeftMe(this);
    }

    /// <summary>Field number for the "member" field.</summary>
    public const int MemberFieldNumber = 1;
    private global::Surf.Proto.MemberAddress member_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.MemberAddress Member {
      get { return member_; }
      set {
        member_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MemberLeftMe);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MemberLeftMe other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Member, other.Member)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (member_ != null) hash ^= Member.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (member_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Member);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (member_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Member);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MemberLeftMe other) {
      if (other == null) {
        return;
      }
      if (other.member_ != null) {
        if (member_ == null) {
          Member = new global::Surf.Proto.MemberAddress();
        }
        Member.MergeFrom(other.Member);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (member_ == null) {
              Member = new global::Surf.Proto.MemberAddress();
            }
            input.ReadMessage(Member);
            break;
          }
        }
      }
    }

  }

  public sealed partial class MemberJoinedMe : pb::IMessage<MemberJoinedMe> {
    private static readonly pb::MessageParser<MemberJoinedMe> _parser = new pb::MessageParser<MemberJoinedMe>(() => new MemberJoinedMe());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MemberJoinedMe> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Surf.Proto.GossipReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberJoinedMe() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberJoinedMe(MemberJoinedMe other) : this() {
      member_ = other.member_ != null ? other.member_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberJoinedMe Clone() {
      return new MemberJoinedMe(this);
    }

    /// <summary>Field number for the "member" field.</summary>
    public const int MemberFieldNumber = 1;
    private global::Surf.Proto.MemberAddress member_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.MemberAddress Member {
      get { return member_; }
      set {
        member_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MemberJoinedMe);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MemberJoinedMe other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Member, other.Member)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (member_ != null) hash ^= Member.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (member_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Member);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (member_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Member);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MemberJoinedMe other) {
      if (other == null) {
        return;
      }
      if (other.member_ != null) {
        if (member_ == null) {
          Member = new global::Surf.Proto.MemberAddress();
        }
        Member.MergeFrom(other.Member);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (member_ == null) {
              Member = new global::Surf.Proto.MemberAddress();
            }
            input.ReadMessage(Member);
            break;
          }
        }
      }
    }

  }

  public sealed partial class MemberFailedForMe : pb::IMessage<MemberFailedForMe> {
    private static readonly pb::MessageParser<MemberFailedForMe> _parser = new pb::MessageParser<MemberFailedForMe>(() => new MemberFailedForMe());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MemberFailedForMe> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Surf.Proto.GossipReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberFailedForMe() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberFailedForMe(MemberFailedForMe other) : this() {
      member_ = other.member_ != null ? other.member_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberFailedForMe Clone() {
      return new MemberFailedForMe(this);
    }

    /// <summary>Field number for the "member" field.</summary>
    public const int MemberFieldNumber = 1;
    private global::Surf.Proto.MemberAddress member_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.MemberAddress Member {
      get { return member_; }
      set {
        member_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MemberFailedForMe);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MemberFailedForMe other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Member, other.Member)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (member_ != null) hash ^= Member.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (member_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Member);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (member_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Member);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MemberFailedForMe other) {
      if (other == null) {
        return;
      }
      if (other.member_ != null) {
        if (member_ == null) {
          Member = new global::Surf.Proto.MemberAddress();
        }
        Member.MergeFrom(other.Member);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (member_ == null) {
              Member = new global::Surf.Proto.MemberAddress();
            }
            input.ReadMessage(Member);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
