// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/hello.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Surf.Proto {

  /// <summary>Holder for reflection information generated from Proto/hello.proto</summary>
  public static partial class HelloReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/hello.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HelloReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFQcm90by9oZWxsby5wcm90bxIEc3VyZhofZ29vZ2xlL3Byb3RvYnVmL3Rp",
            "bWVzdGFtcC5wcm90bxoRcHJvdG8vdHlwZXMucHJvdG8ijAEKClVkcE1lc3Nh",
            "Z2USGgoEcGluZxgBIAEoCzIKLnN1cmYuUGluZ0gAEiAKB3BpbmdSZXEYAiAB",
            "KAsyDS5zdXJmLlBpbmdSZXFIABIYCgNhY2sYAyABKAsyCS5zdXJmLkFja0gA",
            "Eh4KBmFja1JlcRgEIAEoCzIMLnN1cmYuQWNrUmVxSABCBgoEdHlwZSIkCgRQ",
            "aW5nEhwKBmdvc3NpcBgBIAMoCzIMLnN1cmYuR29zc2lwIkwKB1BpbmdSZXES",
            "IwoGbWVtYmVyGAEgASgLMhMuc3VyZi5NZW1iZXJBZGRyZXNzEhwKBmdvc3Np",
            "cBgCIAMoCzIMLnN1cmYuR29zc2lwIgUKA0FjayIvCgZBY2tSZXESJQoIb2ZN",
            "ZW1iZXIYASABKAsyEy5zdXJmLk1lbWJlckFkZHJlc3NCDaoCClN1cmYuUHJv",
            "dG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Surf.Proto.TypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Surf.Proto.UdpMessage), global::Surf.Proto.UdpMessage.Parser, new[]{ "Ping", "PingReq", "Ack", "AckReq" }, new[]{ "Type" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Surf.Proto.Ping), global::Surf.Proto.Ping.Parser, new[]{ "Gossip" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Surf.Proto.PingReq), global::Surf.Proto.PingReq.Parser, new[]{ "Member", "Gossip" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Surf.Proto.Ack), global::Surf.Proto.Ack.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Surf.Proto.AckReq), global::Surf.Proto.AckReq.Parser, new[]{ "OfMember" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UdpMessage : pb::IMessage<UdpMessage> {
    private static readonly pb::MessageParser<UdpMessage> _parser = new pb::MessageParser<UdpMessage>(() => new UdpMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UdpMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Surf.Proto.HelloReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UdpMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UdpMessage(UdpMessage other) : this() {
      switch (other.TypeCase) {
        case TypeOneofCase.Ping:
          Ping = other.Ping.Clone();
          break;
        case TypeOneofCase.PingReq:
          PingReq = other.PingReq.Clone();
          break;
        case TypeOneofCase.Ack:
          Ack = other.Ack.Clone();
          break;
        case TypeOneofCase.AckReq:
          AckReq = other.AckReq.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UdpMessage Clone() {
      return new UdpMessage(this);
    }

    /// <summary>Field number for the "ping" field.</summary>
    public const int PingFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.Ping Ping {
      get { return typeCase_ == TypeOneofCase.Ping ? (global::Surf.Proto.Ping) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Ping;
      }
    }

    /// <summary>Field number for the "pingReq" field.</summary>
    public const int PingReqFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.PingReq PingReq {
      get { return typeCase_ == TypeOneofCase.PingReq ? (global::Surf.Proto.PingReq) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.PingReq;
      }
    }

    /// <summary>Field number for the "ack" field.</summary>
    public const int AckFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.Ack Ack {
      get { return typeCase_ == TypeOneofCase.Ack ? (global::Surf.Proto.Ack) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Ack;
      }
    }

    /// <summary>Field number for the "ackReq" field.</summary>
    public const int AckReqFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.AckReq AckReq {
      get { return typeCase_ == TypeOneofCase.AckReq ? (global::Surf.Proto.AckReq) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.AckReq;
      }
    }

    private object type_;
    /// <summary>Enum of possible cases for the "type" oneof.</summary>
    public enum TypeOneofCase {
      None = 0,
      Ping = 1,
      PingReq = 2,
      Ack = 3,
      AckReq = 4,
    }
    private TypeOneofCase typeCase_ = TypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TypeOneofCase TypeCase {
      get { return typeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearType() {
      typeCase_ = TypeOneofCase.None;
      type_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UdpMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UdpMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Ping, other.Ping)) return false;
      if (!object.Equals(PingReq, other.PingReq)) return false;
      if (!object.Equals(Ack, other.Ack)) return false;
      if (!object.Equals(AckReq, other.AckReq)) return false;
      if (TypeCase != other.TypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (typeCase_ == TypeOneofCase.Ping) hash ^= Ping.GetHashCode();
      if (typeCase_ == TypeOneofCase.PingReq) hash ^= PingReq.GetHashCode();
      if (typeCase_ == TypeOneofCase.Ack) hash ^= Ack.GetHashCode();
      if (typeCase_ == TypeOneofCase.AckReq) hash ^= AckReq.GetHashCode();
      hash ^= (int) typeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (typeCase_ == TypeOneofCase.Ping) {
        output.WriteRawTag(10);
        output.WriteMessage(Ping);
      }
      if (typeCase_ == TypeOneofCase.PingReq) {
        output.WriteRawTag(18);
        output.WriteMessage(PingReq);
      }
      if (typeCase_ == TypeOneofCase.Ack) {
        output.WriteRawTag(26);
        output.WriteMessage(Ack);
      }
      if (typeCase_ == TypeOneofCase.AckReq) {
        output.WriteRawTag(34);
        output.WriteMessage(AckReq);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (typeCase_ == TypeOneofCase.Ping) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ping);
      }
      if (typeCase_ == TypeOneofCase.PingReq) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PingReq);
      }
      if (typeCase_ == TypeOneofCase.Ack) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ack);
      }
      if (typeCase_ == TypeOneofCase.AckReq) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AckReq);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UdpMessage other) {
      if (other == null) {
        return;
      }
      switch (other.TypeCase) {
        case TypeOneofCase.Ping:
          if (Ping == null) {
            Ping = new global::Surf.Proto.Ping();
          }
          Ping.MergeFrom(other.Ping);
          break;
        case TypeOneofCase.PingReq:
          if (PingReq == null) {
            PingReq = new global::Surf.Proto.PingReq();
          }
          PingReq.MergeFrom(other.PingReq);
          break;
        case TypeOneofCase.Ack:
          if (Ack == null) {
            Ack = new global::Surf.Proto.Ack();
          }
          Ack.MergeFrom(other.Ack);
          break;
        case TypeOneofCase.AckReq:
          if (AckReq == null) {
            AckReq = new global::Surf.Proto.AckReq();
          }
          AckReq.MergeFrom(other.AckReq);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Surf.Proto.Ping subBuilder = new global::Surf.Proto.Ping();
            if (typeCase_ == TypeOneofCase.Ping) {
              subBuilder.MergeFrom(Ping);
            }
            input.ReadMessage(subBuilder);
            Ping = subBuilder;
            break;
          }
          case 18: {
            global::Surf.Proto.PingReq subBuilder = new global::Surf.Proto.PingReq();
            if (typeCase_ == TypeOneofCase.PingReq) {
              subBuilder.MergeFrom(PingReq);
            }
            input.ReadMessage(subBuilder);
            PingReq = subBuilder;
            break;
          }
          case 26: {
            global::Surf.Proto.Ack subBuilder = new global::Surf.Proto.Ack();
            if (typeCase_ == TypeOneofCase.Ack) {
              subBuilder.MergeFrom(Ack);
            }
            input.ReadMessage(subBuilder);
            Ack = subBuilder;
            break;
          }
          case 34: {
            global::Surf.Proto.AckReq subBuilder = new global::Surf.Proto.AckReq();
            if (typeCase_ == TypeOneofCase.AckReq) {
              subBuilder.MergeFrom(AckReq);
            }
            input.ReadMessage(subBuilder);
            AckReq = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class Ping : pb::IMessage<Ping> {
    private static readonly pb::MessageParser<Ping> _parser = new pb::MessageParser<Ping>(() => new Ping());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Ping> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Surf.Proto.HelloReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ping() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ping(Ping other) : this() {
      gossip_ = other.gossip_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ping Clone() {
      return new Ping(this);
    }

    /// <summary>Field number for the "gossip" field.</summary>
    public const int GossipFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Surf.Proto.Gossip> _repeated_gossip_codec
        = pb::FieldCodec.ForMessage(10, global::Surf.Proto.Gossip.Parser);
    private readonly pbc::RepeatedField<global::Surf.Proto.Gossip> gossip_ = new pbc::RepeatedField<global::Surf.Proto.Gossip>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Surf.Proto.Gossip> Gossip {
      get { return gossip_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Ping);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Ping other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!gossip_.Equals(other.gossip_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= gossip_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      gossip_.WriteTo(output, _repeated_gossip_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += gossip_.CalculateSize(_repeated_gossip_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Ping other) {
      if (other == null) {
        return;
      }
      gossip_.Add(other.gossip_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            gossip_.AddEntriesFrom(input, _repeated_gossip_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PingReq : pb::IMessage<PingReq> {
    private static readonly pb::MessageParser<PingReq> _parser = new pb::MessageParser<PingReq>(() => new PingReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PingReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Surf.Proto.HelloReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingReq(PingReq other) : this() {
      member_ = other.member_ != null ? other.member_.Clone() : null;
      gossip_ = other.gossip_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingReq Clone() {
      return new PingReq(this);
    }

    /// <summary>Field number for the "member" field.</summary>
    public const int MemberFieldNumber = 1;
    private global::Surf.Proto.MemberAddress member_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.MemberAddress Member {
      get { return member_; }
      set {
        member_ = value;
      }
    }

    /// <summary>Field number for the "gossip" field.</summary>
    public const int GossipFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Surf.Proto.Gossip> _repeated_gossip_codec
        = pb::FieldCodec.ForMessage(18, global::Surf.Proto.Gossip.Parser);
    private readonly pbc::RepeatedField<global::Surf.Proto.Gossip> gossip_ = new pbc::RepeatedField<global::Surf.Proto.Gossip>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Surf.Proto.Gossip> Gossip {
      get { return gossip_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PingReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PingReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Member, other.Member)) return false;
      if(!gossip_.Equals(other.gossip_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (member_ != null) hash ^= Member.GetHashCode();
      hash ^= gossip_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (member_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Member);
      }
      gossip_.WriteTo(output, _repeated_gossip_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (member_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Member);
      }
      size += gossip_.CalculateSize(_repeated_gossip_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PingReq other) {
      if (other == null) {
        return;
      }
      if (other.member_ != null) {
        if (member_ == null) {
          Member = new global::Surf.Proto.MemberAddress();
        }
        Member.MergeFrom(other.Member);
      }
      gossip_.Add(other.gossip_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (member_ == null) {
              Member = new global::Surf.Proto.MemberAddress();
            }
            input.ReadMessage(Member);
            break;
          }
          case 18: {
            gossip_.AddEntriesFrom(input, _repeated_gossip_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Ack : pb::IMessage<Ack> {
    private static readonly pb::MessageParser<Ack> _parser = new pb::MessageParser<Ack>(() => new Ack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Ack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Surf.Proto.HelloReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ack(Ack other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ack Clone() {
      return new Ack(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Ack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Ack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Ack other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class AckReq : pb::IMessage<AckReq> {
    private static readonly pb::MessageParser<AckReq> _parser = new pb::MessageParser<AckReq>(() => new AckReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AckReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Surf.Proto.HelloReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AckReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AckReq(AckReq other) : this() {
      ofMember_ = other.ofMember_ != null ? other.ofMember_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AckReq Clone() {
      return new AckReq(this);
    }

    /// <summary>Field number for the "ofMember" field.</summary>
    public const int OfMemberFieldNumber = 1;
    private global::Surf.Proto.MemberAddress ofMember_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.MemberAddress OfMember {
      get { return ofMember_; }
      set {
        ofMember_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AckReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AckReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OfMember, other.OfMember)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ofMember_ != null) hash ^= OfMember.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ofMember_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OfMember);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ofMember_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OfMember);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AckReq other) {
      if (other == null) {
        return;
      }
      if (other.ofMember_ != null) {
        if (ofMember_ == null) {
          OfMember = new global::Surf.Proto.MemberAddress();
        }
        OfMember.MergeFrom(other.OfMember);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (ofMember_ == null) {
              OfMember = new global::Surf.Proto.MemberAddress();
            }
            input.ReadMessage(OfMember);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
