// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Surf.Proto {

  /// <summary>Holder for reflection information generated from Proto/types.proto</summary>
  public static partial class TypesReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFQcm90by90eXBlcy5wcm90bxIEc3VyZiJDCg1NZW1iZXJBZGRyZXNzEgwK",
            "AnY0GAEgASgHSAASDAoCdjYYAiABKAxIABIMCgRwb3J0GAMgASgHQggKBmlw",
            "QWRkciJ7CgZHb3NzaXASNgoSZmFpbGVkVG9QaW5nTWVtYmVyGAEgASgLMhgu",
            "c3VyZi5GYWlsZWRUb1BpbmdNZW1iZXJIABIqCgxtZW1iZXJKb2luZWQYAiAB",
            "KAsyEi5zdXJmLk1lbWJlckpvaW5lZEgAQg0KC21lc3NhZ2VUeXBlIjkKEkZh",
            "aWxlZFRvUGluZ01lbWJlchIjCgZtZW1iZXIYASABKAsyEy5zdXJmLk1lbWJl",
            "ckFkZHJlc3MiMwoMTWVtYmVySm9pbmVkEiMKBm1lbWJlchgBIAEoCzITLnN1",
            "cmYuTWVtYmVyQWRkcmVzc0INqgIKU3VyZi5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Surf.Proto.MemberAddress), global::Surf.Proto.MemberAddress.Parser, new[]{ "V4", "V6", "Port" }, new[]{ "IpAddr" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Surf.Proto.Gossip), global::Surf.Proto.Gossip.Parser, new[]{ "FailedToPingMember", "MemberJoined" }, new[]{ "MessageType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Surf.Proto.FailedToPingMember), global::Surf.Proto.FailedToPingMember.Parser, new[]{ "Member" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Surf.Proto.MemberJoined), global::Surf.Proto.MemberJoined.Parser, new[]{ "Member" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MemberAddress : pb::IMessage<MemberAddress> {
    private static readonly pb::MessageParser<MemberAddress> _parser = new pb::MessageParser<MemberAddress>(() => new MemberAddress());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MemberAddress> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Surf.Proto.TypesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberAddress() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberAddress(MemberAddress other) : this() {
      port_ = other.port_;
      switch (other.IpAddrCase) {
        case IpAddrOneofCase.V4:
          V4 = other.V4;
          break;
        case IpAddrOneofCase.V6:
          V6 = other.V6;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberAddress Clone() {
      return new MemberAddress(this);
    }

    /// <summary>Field number for the "v4" field.</summary>
    public const int V4FieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint V4 {
      get { return ipAddrCase_ == IpAddrOneofCase.V4 ? (uint) ipAddr_ : 0; }
      set {
        ipAddr_ = value;
        ipAddrCase_ = IpAddrOneofCase.V4;
      }
    }

    /// <summary>Field number for the "v6" field.</summary>
    public const int V6FieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString V6 {
      get { return ipAddrCase_ == IpAddrOneofCase.V6 ? (pb::ByteString) ipAddr_ : pb::ByteString.Empty; }
      set {
        ipAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        ipAddrCase_ = IpAddrOneofCase.V6;
      }
    }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 3;
    private uint port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    private object ipAddr_;
    /// <summary>Enum of possible cases for the "ipAddr" oneof.</summary>
    public enum IpAddrOneofCase {
      None = 0,
      V4 = 1,
      V6 = 2,
    }
    private IpAddrOneofCase ipAddrCase_ = IpAddrOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IpAddrOneofCase IpAddrCase {
      get { return ipAddrCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearIpAddr() {
      ipAddrCase_ = IpAddrOneofCase.None;
      ipAddr_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MemberAddress);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MemberAddress other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (V4 != other.V4) return false;
      if (V6 != other.V6) return false;
      if (Port != other.Port) return false;
      if (IpAddrCase != other.IpAddrCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ipAddrCase_ == IpAddrOneofCase.V4) hash ^= V4.GetHashCode();
      if (ipAddrCase_ == IpAddrOneofCase.V6) hash ^= V6.GetHashCode();
      if (Port != 0) hash ^= Port.GetHashCode();
      hash ^= (int) ipAddrCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ipAddrCase_ == IpAddrOneofCase.V4) {
        output.WriteRawTag(13);
        output.WriteFixed32(V4);
      }
      if (ipAddrCase_ == IpAddrOneofCase.V6) {
        output.WriteRawTag(18);
        output.WriteBytes(V6);
      }
      if (Port != 0) {
        output.WriteRawTag(29);
        output.WriteFixed32(Port);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ipAddrCase_ == IpAddrOneofCase.V4) {
        size += 1 + 4;
      }
      if (ipAddrCase_ == IpAddrOneofCase.V6) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(V6);
      }
      if (Port != 0) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MemberAddress other) {
      if (other == null) {
        return;
      }
      if (other.Port != 0) {
        Port = other.Port;
      }
      switch (other.IpAddrCase) {
        case IpAddrOneofCase.V4:
          V4 = other.V4;
          break;
        case IpAddrOneofCase.V6:
          V6 = other.V6;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            V4 = input.ReadFixed32();
            break;
          }
          case 18: {
            V6 = input.ReadBytes();
            break;
          }
          case 29: {
            Port = input.ReadFixed32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Gossip : pb::IMessage<Gossip> {
    private static readonly pb::MessageParser<Gossip> _parser = new pb::MessageParser<Gossip>(() => new Gossip());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Gossip> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Surf.Proto.TypesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gossip() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gossip(Gossip other) : this() {
      switch (other.MessageTypeCase) {
        case MessageTypeOneofCase.FailedToPingMember:
          FailedToPingMember = other.FailedToPingMember.Clone();
          break;
        case MessageTypeOneofCase.MemberJoined:
          MemberJoined = other.MemberJoined.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gossip Clone() {
      return new Gossip(this);
    }

    /// <summary>Field number for the "failedToPingMember" field.</summary>
    public const int FailedToPingMemberFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.FailedToPingMember FailedToPingMember {
      get { return messageTypeCase_ == MessageTypeOneofCase.FailedToPingMember ? (global::Surf.Proto.FailedToPingMember) messageType_ : null; }
      set {
        messageType_ = value;
        messageTypeCase_ = value == null ? MessageTypeOneofCase.None : MessageTypeOneofCase.FailedToPingMember;
      }
    }

    /// <summary>Field number for the "memberJoined" field.</summary>
    public const int MemberJoinedFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.MemberJoined MemberJoined {
      get { return messageTypeCase_ == MessageTypeOneofCase.MemberJoined ? (global::Surf.Proto.MemberJoined) messageType_ : null; }
      set {
        messageType_ = value;
        messageTypeCase_ = value == null ? MessageTypeOneofCase.None : MessageTypeOneofCase.MemberJoined;
      }
    }

    private object messageType_;
    /// <summary>Enum of possible cases for the "messageType" oneof.</summary>
    public enum MessageTypeOneofCase {
      None = 0,
      FailedToPingMember = 1,
      MemberJoined = 2,
    }
    private MessageTypeOneofCase messageTypeCase_ = MessageTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageTypeOneofCase MessageTypeCase {
      get { return messageTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMessageType() {
      messageTypeCase_ = MessageTypeOneofCase.None;
      messageType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Gossip);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Gossip other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FailedToPingMember, other.FailedToPingMember)) return false;
      if (!object.Equals(MemberJoined, other.MemberJoined)) return false;
      if (MessageTypeCase != other.MessageTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (messageTypeCase_ == MessageTypeOneofCase.FailedToPingMember) hash ^= FailedToPingMember.GetHashCode();
      if (messageTypeCase_ == MessageTypeOneofCase.MemberJoined) hash ^= MemberJoined.GetHashCode();
      hash ^= (int) messageTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (messageTypeCase_ == MessageTypeOneofCase.FailedToPingMember) {
        output.WriteRawTag(10);
        output.WriteMessage(FailedToPingMember);
      }
      if (messageTypeCase_ == MessageTypeOneofCase.MemberJoined) {
        output.WriteRawTag(18);
        output.WriteMessage(MemberJoined);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (messageTypeCase_ == MessageTypeOneofCase.FailedToPingMember) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FailedToPingMember);
      }
      if (messageTypeCase_ == MessageTypeOneofCase.MemberJoined) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MemberJoined);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Gossip other) {
      if (other == null) {
        return;
      }
      switch (other.MessageTypeCase) {
        case MessageTypeOneofCase.FailedToPingMember:
          if (FailedToPingMember == null) {
            FailedToPingMember = new global::Surf.Proto.FailedToPingMember();
          }
          FailedToPingMember.MergeFrom(other.FailedToPingMember);
          break;
        case MessageTypeOneofCase.MemberJoined:
          if (MemberJoined == null) {
            MemberJoined = new global::Surf.Proto.MemberJoined();
          }
          MemberJoined.MergeFrom(other.MemberJoined);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Surf.Proto.FailedToPingMember subBuilder = new global::Surf.Proto.FailedToPingMember();
            if (messageTypeCase_ == MessageTypeOneofCase.FailedToPingMember) {
              subBuilder.MergeFrom(FailedToPingMember);
            }
            input.ReadMessage(subBuilder);
            FailedToPingMember = subBuilder;
            break;
          }
          case 18: {
            global::Surf.Proto.MemberJoined subBuilder = new global::Surf.Proto.MemberJoined();
            if (messageTypeCase_ == MessageTypeOneofCase.MemberJoined) {
              subBuilder.MergeFrom(MemberJoined);
            }
            input.ReadMessage(subBuilder);
            MemberJoined = subBuilder;
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// failed to ping member
  /// </summary>
  public sealed partial class FailedToPingMember : pb::IMessage<FailedToPingMember> {
    private static readonly pb::MessageParser<FailedToPingMember> _parser = new pb::MessageParser<FailedToPingMember>(() => new FailedToPingMember());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FailedToPingMember> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Surf.Proto.TypesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FailedToPingMember() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FailedToPingMember(FailedToPingMember other) : this() {
      member_ = other.member_ != null ? other.member_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FailedToPingMember Clone() {
      return new FailedToPingMember(this);
    }

    /// <summary>Field number for the "member" field.</summary>
    public const int MemberFieldNumber = 1;
    private global::Surf.Proto.MemberAddress member_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.MemberAddress Member {
      get { return member_; }
      set {
        member_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FailedToPingMember);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FailedToPingMember other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Member, other.Member)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (member_ != null) hash ^= Member.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (member_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Member);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (member_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Member);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FailedToPingMember other) {
      if (other == null) {
        return;
      }
      if (other.member_ != null) {
        if (member_ == null) {
          Member = new global::Surf.Proto.MemberAddress();
        }
        Member.MergeFrom(other.Member);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (member_ == null) {
              Member = new global::Surf.Proto.MemberAddress();
            }
            input.ReadMessage(Member);
            break;
          }
        }
      }
    }

  }

  public sealed partial class MemberJoined : pb::IMessage<MemberJoined> {
    private static readonly pb::MessageParser<MemberJoined> _parser = new pb::MessageParser<MemberJoined>(() => new MemberJoined());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MemberJoined> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Surf.Proto.TypesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberJoined() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberJoined(MemberJoined other) : this() {
      member_ = other.member_ != null ? other.member_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberJoined Clone() {
      return new MemberJoined(this);
    }

    /// <summary>Field number for the "member" field.</summary>
    public const int MemberFieldNumber = 1;
    private global::Surf.Proto.MemberAddress member_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Surf.Proto.MemberAddress Member {
      get { return member_; }
      set {
        member_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MemberJoined);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MemberJoined other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Member, other.Member)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (member_ != null) hash ^= Member.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (member_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Member);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (member_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Member);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MemberJoined other) {
      if (other == null) {
        return;
      }
      if (other.member_ != null) {
        if (member_ == null) {
          Member = new global::Surf.Proto.MemberAddress();
        }
        Member.MergeFrom(other.Member);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (member_ == null) {
              Member = new global::Surf.Proto.MemberAddress();
            }
            input.ReadMessage(Member);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
